# JVM Memory Allocation and UTF-8 Encoding
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX Migration Flags
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin Code Style
kotlin.code.style=official

# Disable configuration cache during initial bootstrapping
org.gradle.configuration-cache=false
